/run/verbose 0
/control/verbose 0
/tracking/verbose 0
/process/optical/verbose 0
/process/optical/boundary/verbose 0


/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/LArAbsLength 50

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_1
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 500



/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/LArAbsLength 100

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_2
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 500


/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/LArAbsLength 500

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_3
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 500

/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/LArAbsLength 1500

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_4
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 500