/run/verbose 0
/control/verbose 0
/tracking/verbose 0
/process/optical/verbose 0
/process/optical/boundary/verbose 0



/run/initialize

/mydetector/SourcePosAlphaZ 0. 30 0.
/mydetector/MainScintYield 40000.
/mydetector/ESRreflectivity 0.83
/mydetector/LArAbsLength 200
/process/optical/scintillation/setTrackSecondariesFirst true

/analysis/setFileName wls_0_30
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 250


/mydetector/SourcePosAlphaZ 0. 22.5 0. 
/mydetector/ESRreflectivity 0.83
/mydetector/LArAbsLength 200
/run/initialize
/mydetector/MainScintYield 40000.

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_22p5
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 250

/mydetector/SourcePosAlphaZ 0. -7.5 0.
/mydetector/ESRreflectivity 0.83
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/LArAbsLength 200

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_m7p5
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 250



/mydetector/SourcePosAlphaZ 0. -45 0. 
/mydetector/ESRreflectivity 0.83
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/LArAbsLength 200
/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_m45
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 250


/mydetector/SourcePosAlphaZ 50. 20 0.
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/ESRreflectivity 0.83
/mydetector/LArAbsLength 200
/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_50_20
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 250


/mydetector/SourcePosAlphaZ 50. -7.5 0. 
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/ESRreflectivity 0.83
/mydetector/LArAbsLength 200
/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_50_m7p5
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 250

/mydetector/SourcePosAlphaZ 50. -45 0. 
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/ESRreflectivity 0.83
/mydetector/LArAbsLength 200
/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_50_m45
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 250

/mydetector/SourcePosAlphaZ -50. 29 0. 
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/ESRreflectivity 0.83
/mydetector/LArAbsLength 200
/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_m50_20
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 250

/mydetector/SourcePosAlphaZ -50. 26.25 0. 
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/ESRreflectivity 0.83
/mydetector/LArAbsLength 200
/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_m50_m7p5
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 250

/mydetector/SourcePosAlphaZ -50. 22.5 0.  
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/ESRreflectivity 0.83
/mydetector/LArAbsLength 200
/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_m50_m45
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 250