/run/verbose 0
/control/verbose 0
/tracking/verbose 0
/process/optical/verbose 0
/process/optical/boundary/verbose 0


/mydetector/SourcePosAlphaZ 0. 0. 0.
/mydetector/ESRreflectivity 0.83
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/ESRreflectivity 0.83

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_0
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 500


/mydetector/SourcePosAlphaZ 0. -20. 0.
/mydetector/ESRreflectivity 0.83
/run/initialize
/mydetector/MainScintYield 40000.

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_m20
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 500

/mydetector/SourcePosAlphaZ 0. 20. 0.
/mydetector/ESRreflectivity 0.83
/run/initialize
/mydetector/MainScintYield 40000.

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_20
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 500



/mydetector/SourcePosAlphaZ 0. -40. 0.
/mydetector/ESRreflectivity 0.83
/run/initialize
/mydetector/MainScintYield 40000.

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_m40
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 500


/mydetector/SourcePosAlphaZ 0. 40. 0.
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/ESRreflectivity 0.83

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_40
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 500


/mydetector/SourcePosAlphaZ -50. 40. 0.
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/ESRreflectivity 0.83

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_40_am50
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 500

/mydetector/SourcePosAlphaZ 50. 40. 0.
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/ESRreflectivity 0.83

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_40_a50
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 500

/mydetector/SourcePosAlphaZ -50. -40. 0.
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/ESRreflectivity 0.83

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_m40_am50
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 500

/mydetector/SourcePosAlphaZ 50. -40. 0.
/run/initialize
/mydetector/MainScintYield 40000.
/mydetector/ESRreflectivity 0.83

/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls_0_m40_a50
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 500

