#/run/numberOfThreads 1
/run/verbose 0
/control/verbose 0
/tracking/verbose 0
/process/optical/verbose 0
/process/optical/boundary/verbose 0


/mydetector/SourcePosAlphaZ 0. 30 0.
/mydetector/ESRreflectivity 0.83
/mydetector/LArAbsLength 50
/process/optical/scintillation/setTrackSecondariesFirst true

/run/reinitializeGeometry
/vis/scene/notifyHandlers
/vis/viewer/update
/run/initialize

#So that only a few photons are created and the paths are visible
/mydetector/MainScintYield 10000.



/process/optical/scintillation/setTrackSecondariesFirst true
/analysis/setFileName wls
/analysis/h1/set 0 1000 0 0.1
/analysis/h1/set 1 100 0 100
/analysis/h1/set 2 100 0 1500
/analysis/h1/set 3 10 0.3 0.7
/run/beamOn 1

#*jiqbYv-2zobti